// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haziaggucttnvrxwazvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhemlhZ2d1Y3R0bnZyeHdhenZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzY3MDQsImV4cCI6MjA2MzY1MjcwNH0.yoXCffJpgKDcjIVgtKBLNaPPikOyhAGaHRzxbLcrQkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);